### ISSUE TITLE
how to use private repo?

### ISSUE THREAD

**Issue by hiphapis** [radekstepan/burnchart#103]
i did try team private repo.
but `burnchart` does not loaded it.

i saw `src/modules/github/request.coffee`
in this file, sent token with header
```coffee
ready ->
  data = _.defaults
    'path':   "/repos/#{owner}/#{name}"
    'headers':  headers user.data.github?.accessToken
  , defaults.github

  request data, cb
```
i checked `headers` token value. but it's not matched `user.data.github.accessToken` and `user.data.token`
hm.. strange

anyway. let me know how to change for private repo.

**Comment by radekstepan** [comment]
Hmm bummer, I am using it with a private repo and don't experience the same issue.

Are you using GitHub Enterprise by any chance?
Are you logged-in by clicking on the yellow button in the top right corner?

The `repo` scope we are making the requests with should give you access to [private repos](https://developer.github.com/v3/oauth/#scopes).

**Comment by hiphapis** [comment]
Hmm. Why did this happen to me ;(

sure. i did pay to github for organization
absolutely logged in ;)

could i do some setting?

**Comment by radekstepan** [comment]
Can you see any error message in the developer tools of your browser?

For example Ctrl + Shift + J in Chrome.

**Comment by hiphapis** [comment]
it's 404. i guess the problem is Scope.
now i'm trying https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists

**Comment by radekstepan** [comment]
OK, here is where the scope is being set:

https://github.com/radekstepan/burnchart/blob/master/src/models/firebase.coffee#L26

Would you know how to rebuild the app to try a different scope?

**Comment by hiphapis** [comment]
`rake build` is right?

```
$curl -H "Authorization: token TOKEN" https://api.github.com/users/Stayes -I 
X-OAuth-Scopes: repo
X-Accepted-OAuth-Scopes: user
```
i want to add scope 'repo'
i did make a new application (followed https://developer.github.com/v3/oauth/)
and did try change OAuth settings but i'm failed. because firebase.

Hm.. please give me some hint ;(
i lost way

**Comment by radekstepan** [comment]
The scope is already `repo`.

**Comment by hiphapis** [comment]
right. code has already `repo`
but `X-Accepted-OAuth-Scopes` has not `repo` ;(

**Comment by radekstepan** [comment]
I bumped all the dependencies, but the latest version of Firebase behaves like before, leaving `X-Accepted-OAuth-Scopes` blank. You are welcome to try [http://radekstepan.com/burnchart](http://radekstepan.com/burnchart) now and see if it helps any.

**Comment by hiphapis** [comment]
![image](https://cloud.githubusercontent.com/assets/18629/6795237/b962ff2e-d220-11e4-840c-36a27ad051a6.png)
![image](https://cloud.githubusercontent.com/assets/18629/6795264/0b62591e-d221-11e4-9174-4080831fc1e9.png)
hahaha ;(

**Comment by radekstepan** [comment]
OK don't know what else to try. I see it doesn't work for you, but we are using official `Firebase` lib to do the auth, so if anything it may be something on their end that they may fix in the future. The lib is minified so no easy feat to debug it.

**Comment by hiphapis** [comment]
Finally i solved this issue.
hiphapis(me) is owner but it's not creator.
when i logged creator then this problem is solved. :p
but https://burnchart.firebaseapp.com/ this site are still has problem
Thanks @radekstepan !!
this chart is very helpful to me!
appreciation your help and burnchart!!!

**Comment by radekstepan** [comment]
But I've seen you try to access a private repo associated with your user-account no? Either way I am glad it is solved.

Yeah don't use [https://burnchart.firebaseapp.com](https://burnchart.firebaseapp.com) it is used for testing and I will bring it down now.
