### ISSUE TITLE
js and css links broken

### ISSUE THREAD

**Issue by pbinkley** [radekstepan/burnchart#104]
I don't know if it's something about my installation, but I was getting a blank screen until I edited index.html to change the names of the css and js files from "app.bundle.css" to "app.bundle.min.css", and from "app.bundle.js" to "app.bundle.min.js".

**Comment by radekstepan** [comment]
Hi, if you are running the app in development mode, then keep filenames as
is. But if you are running it in production, the "bundle" suffix is needed.
Check out the gh-pages branch that is used to serve the app.

I am in a phone so sorry for the short reply.

**Comment by radekstepan** [comment]
Typo, I meant "min" suffix.
