### ISSUE TITLE
Make charts publicly linkable.

### ISSUE THREAD

**Issue by nathan-at-least** [radekstepan/burnchart#116]
I am investigating burndown charts for github, and just tried this one out. I like how quickly I got it set up. However, I can't paste the link in other browsers to reproduce the same chart, even though the link has the project name:

http://radekstepan.com/burnchart/#!/zcash/zcash/23

This would be a necessary feature for our use, since we frequently share links across our remote team.

**Comment by radekstepan** [comment]
I see, thanks for reporting that. It's a bug since if I add a `zcash/zcash` repo first, it works.

**Comment by radekstepan** [comment]
OK, made a fix and wrote a test for it. Please check it works for you in your environment.

**Comment by nathan-at-least** [comment]
I just verified the links to a specific milestone work for me in two
different browsers. Thanks!

On Thu, Mar 24, 2016 at 6:45 PM, Radek Stepan <notifications@github.com>
wrote:

> OK, made a fix and wrote a test for it. Please check it works for you in
> your environment.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radekstepan/burnchart/issues/116#issuecomment-201104007>
>



-- 
Nathan Wilcox
Least Authoritarian

email: nathan@leastauthority.com
twitter: @least_nathan

**Comment by radekstepan** [comment]
Perfect, thanks for verifying.
