### ISSUE TITLE
A good way to embed the chart into a dashboard?

### ISSUE THREAD

**Issue by sethladd** [radekstepan/burnchart#118]
Hi, We really like the burndown chart and would like to embed into a dashboard that we run internally. Is there a recommended way of fetching the chart and displaying inside of an iframe or similar? Thanks!

**Comment by radekstepan** [comment]
Hi, glad you are liking it. Would you like to run the app without the chrome so you could iframe it? Is GitHub auth needed?

Basically, would a burnchart with a theme that removes the red bar at the top and asks you to login with GitHub on startup do the trick?

**Comment by sethladd** [comment]
> Would you like to run the app without the chrome so you could iframe it?

Yes, we would like to iframe it. However, ideally we don't want to run the app ourselves. We would like to use your hosted version.

Github auth is not needed. Our repos are public.

Just a page with the graph and legend would be really nice. Thanks!

(of course, you could add a small "brought to you by ..." :)

**Comment by radekstepan** [comment]
When you say legend, do you mean the axes on the left and bottom?

If so then I think I got it. I think this would be best handled by a theme that goes `display:none` on the chrome. Chrome could be set via settings and could be override via query string params. So to get a raw chart you'd for example do something like this which you could iframe:

http://radekstepan.com/burnchart/#!/radekstepan/burnchart/2?theme=blank

Would that work?

**Comment by sethladd** [comment]
Yeah, I think so! Bonus points if we can add parameters for width and
height of the content. :)

Thanks!

**Comment by radekstepan** [comment]
Hi, both theming and querystring config are now in. Below is an example of how the app looks like with the main "red" theme switched off. If you are still interested I'd encourage you to create your ideal theme file and deploy somewhere like GitHub Pages. There are instructions in the [README](https://github.com/radekstepan/burnchart#url-query-string) and of course I am here to help.

(https://cloud.githubusercontent.com/assets/195584/15901337/ea23e284-2d70-11e6-8f61-0dbca82f1b53.png)

**Comment by sethladd** [comment]
Thank you! When I go to http://radekstepan.com/burnchart/#!/radekstepan/burnchart/2?theme=raw I still see the red. Was your new "theme=raw" feature deployed to your hosted version?

**Comment by radekstepan** [comment]
Hi, it's the other way round:

http://radekstepan.com/burnchart/?theme=raw#!/radekstepan/burnchart/2
