### ISSUE TITLE
Cross-origin requests that require preflights ?

### ISSUE THREAD

**Issue by marttinn** [radekstepan/burnchart#119]
Hey man! Looks amazing but I cloned and tried and then went over to your demo and found out this mistake in both of them: 
```
XMLHttpRequest cannot load https://api.github.com/repos/mbostock/d3/milestones?state=open&sort=due_date&direction=asc. 
The request was redirected to 'https://api.github.com/repositories/943149/milestones?state=open&sort=due_date&direction=asc', 
which is disallowed for cross-origin requests that require preflight.
```
Thus is not working right now :(

**Comment by radekstepan** [comment]
Thank for letting me know!

I will look at this when I have a minute, since this is quite critical. If you have time in the meantime, the relevant request code is in `src/js/modules/github/request.js`.

**Comment by radekstepan** [comment]
Post-mortem: `mbostock/d3` is now `d3/d3` (one of the demo repositories) and there was a bug in how we handle the redirect request errors, stopping the whole app in its tracks.
