### ISSUE TITLE
Cannot create legacy firebase anymore

### ISSUE THREAD

**Issue by klarkc** [radekstepan/burnchart#122]
Hello, I am trying to create a new project with my own firebase database, but I am receiving an warning on authentication:

> We have detected that you are using the v2.x or lower authentication SDKs with a project that was created at console.firebase.google.com. You must use the 3.0.0 or greater authentication SDKs with projects that have been created in the new console.

[Searching on the internet](https://groups.google.com/d/msg/firebase-talk/6stRgevwkBk/nd3RR2GVBAAJ), it seems that new firebase accounts cannot have access to the legacy firebase console, so I am blocked here. Any advice on this?

**Comment by klarkc** [comment]
Might be related: https://firebase.google.com/support/guides/firebase-web

**Comment by radekstepan** [comment]
Good point, thanks for the guide, will look into it!

**Comment by radekstepan** [comment]
OK, I've imported the legacy Firebase project into Google Firebase. One thing I struggled with was getting the GitHub auth token after the user is already signed in. So now, reloading the whole app in the browser will disregard any signed-in user and one has to re-sign with GitHub. To then fetch the projects anew I've added a "Refresh Projects" button to the bottom of the main table.
