### ISSUE TITLE
How to Specify label through URL

### ISSUE THREAD

**Issue by acouch** [radekstepan/burnchart#123]
I'm trying to view a chart using the labels setting to determine issue size.

When I try to create a URL to view this: http://radekstepan.com/burnchart/?theme=raw&chart[points]=LABEL#!/acouch/Action-Priority-Matrix

I get a console error: 

```
bundle.min.js:37 Uncaught 500
```

I have issues with the default "size X" label. Am I creating the URL correctly?

**Comment by acouch** [comment]
To answer my own question, I was using ``LABEL`` instead of ``LABELS``. This should work:

http://radekstepan.com/burnchart/?theme=raw&chart[points]=LABELS#!/user/repo

**Comment by radekstepan** [comment]
Great, I am glad it works for you now.
