### ISSUE TITLE
Radar chart spokes disappears on mouse hovering 

### ISSUE THREAD

**Issue by vasu-vvp** [radekstepan/burnchart#127]
I have tried this under E-chart demo for Radar chart. It seems this is a bug? 
using following data:
-------------------------------------------------------------------------------------------------
option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
    },
    radar: {
        // shape: 'circle',
        name: {
            textStyle: {
                color: '#fff',
                backgroundColor: '#999',
                borderRadius: 3,
                padding: [3, 5]
           }
        },
        indicator: [
           { name: '销售（sales）', max: 6500},
           { name: '管理（Administration）', max: 16000},
           { name: '信息技术（Information Techology）', max: 30000},
           { name: '客服（Customer Support）', max: 38000},
           { name: '研发（Development）', max: 52000},
           { name: '市场（Marketing）', max: 25000}
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [null, 10000, 28000, 35000, 50000, 19000],
                name : '预算分配（Allocated Budget）'
            }
        ]
    }]
};

-------------------------------------------------------------------------------------------------

For values in data observe that first value of an array is "null".
Now radar is rendered. Hover a mouse on red spokes of radar. You will observe that these red spokes disappears.

Refer image :
![image](https://user-images.githubusercontent.com/30551082/33256472-2b9ee232-d378-11e7-8d12-e17b54f26b06.png)

Thanks!

**Comment by radekstepan** [comment]
Wrong project.
